name: Feature
description: Request a new feature
labels: [enhancement]
body:
  - type: textarea
    id: what
    attributes: { label: What should be built?, placeholder: Clear user story + acceptance criteria }
  - type: textarea
    id: how
    attributes: { label: How to implement (sketch) }
  - type: checkboxes
    id: ac
    attributes:
      label: Acceptance criteria
      options:
        - label: Builds locally
        - label: Code reviewed
        - label: Screenshots/logs attached
