name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "feat/mvp-scan" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Build Debug
        run: ./gradlew assembleDebug
      - name: Upload APK
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: PhantomScout-debug-apk
          path: app/build/outputs/apk/debug/*.apk
